version: 2

sources:
  - name: staging
    database: spatial-vision-412003
     # For postgres:
      #database: production
    schema: ny_taxi

      # loaded_at_field: record_loaded_at
    tables:
      - name: green_taxi_2022_non_partitoned
      - name: yellow_tripdata_non_partitoned
         # freshness:
           # error_after: {count: 6, period: hour}
