version: 2

sources:
  - name: staging
    database: spatial-vision-412003
     # For postgres:
      #database: production
    schema: ny_taxi

      # loaded_at_field: record_loaded_at
    tables:
      - name: fhv_non_partitoned_2019
